version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: install packages required by Electron
          command: sudo apt-get install libgtk-3-0 libxss1 libgconf2-4 libnss3 libasound2
      - run:
          name: start display server so Electron can run headless
          command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1
          background: true
      - checkout

      - run: npm install # this automatically runs "npm prepare" too
        # Note that for CI to work properly, our lerna command for "npm prepare" in package.json needs to 
        # have "--concurrency=2", otherwise we may run out of memory. This is a known issue with Lerna.
      - run: npm run lint
      - run: npm run build

      - run: mkdir -p reports/junit
      - run:
          command: cd ~/project/packages/ldclient-electron && npm run test:junit
          environment:
            JEST_JUNIT_OUTPUT: "./reports/junit/electron-test-results.xml"
            DISPLAY: ":99.0"  # so Electron will use xvfb

      - run: cd ~/project && npm run check-typescript
      - store_test_results:
          path: reports/junit/
      - store_artifacts:
          path: reports/junit/
